### ISSUE TITLE
ep5 - PCA video link takes over the page when clicked 

### ISSUE THREAD

**Issue by murraycadzow** [GenomicsAotearoa/scRNA-seq-data-analysis#2]
Clicking the link for the pca video 
https://github.com/GenomicsAotearoa/scRNA-seq-data-analysis/blob/4b8dec8440026840e0240242416be0332d21c2e7/docs/episodes%20/5.md?plain=1#L133

 makes the video replace the page, can it be switched to have a target of a new window/tab?

**Comment by DininduSenanayake** [comment]
I have added `mkdocs-open-in-new-tab` which takes care of it . i.e. All of the outgoing links will open in a new tab
